name: CMake

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: change file timestamp to commit date
      run: ./git_commit_date.sh
    - name: install cmake
      run: |
        sudo apt update -y
        sudo apt install cmake -y
    - name: install jinja2
      run: sudo pip install jinja2
    - name: cmake build
      run: |
        mkdir build
        cmake -H. -Bbuild
    - name: make
      run: (cd build && make)
    - name: verify
      run: |
        python3 verify.py build --all
        cp build/verify_results.json .ds_verify/
    - name: generate verify html
      run: python3 generate.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.5.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: ds_verify action
        COMMIT_AUTHOR_EMAIL: niuez.graph@gmail.com
        COMMIT_AUTHOR_NAME: niuez
        PULL_REQUEST_TITLE: 'ds_verify'
        PULL_REQUEST_BODY: |
          ds_verify action
        PULL_REQUEST_BRANCH: ds_verify
        BRANCH_SUFFIX: none
    - name: Check output environment variable
      run: echo "Pull Request Number - $PULL_REQUEST_NUMBER"
